paths:
  /products:
    get:
      summary: Obtiene todos los productos
      parameters:
        - name: limit
          in: query
          description: Número de productos a devolver
          schema:
            type: integer
            example: 10
        - name: sort
          in: query
          description: Criterio de ordenamiento
          schema:
            type: string
            example: price
        - name: page
          in: query
          description: Página de resultados
          schema:
            type: integer
            example: 1
        - name: query
          in: query
          description: Consulta de búsqueda de productos
          schema:
            type: string
            example: electronics
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    description:
                      type: string
                    price:
                      type: number
                    thumbnails:
                      type: array
                      items:
                        type: string
                    code:
                      type: string
                    stock:
                      type: integer
                    status:
                      type: boolean
                    category:
                      type: string
        '500':
          description: Error en el servidor
    post:
      summary: Agrega un nuevo producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Título del producto
                  example: Product Name
                description:
                  type: string
                  description: Descripción del producto
                  example: Product Description
                price:
                  type: number
                  description: Precio del producto
                  example: 19.99
                thumbnails:
                  type: array
                  items:
                    type: string
                  description: Imágenes del producto
                  example:
                    - https://example.com/image1.jpg
                    - https://example.com/image2.jpg
                code:
                  type: string
                  description: Código del producto
                  example: 12345
                stock:
                  type: integer
                  description: Cantidad en stock
                  example: 100
                status:
                  type: boolean
                  description: Estado del producto (disponible o no)
                  example: true
                category:
                  type: string
                  description: Categoría del producto
                  example: electronics
      responses:
        '201':
          description: Producto agregado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  price:
                    type: number
                  thumbnails:
                    type: array
                    items:
                      type: string
                  code:
                    type: string
                  stock:
                    type: integer
                  status:
                    type: boolean
                  category:
                    type: string
        '400':
          description: Solicitud inválida (por ejemplo, datos de entrada no válidos)
        '500':
          description: Error en el servidor

  /products/fakeProducts/{qty}:
    get:
      summary: Genera productos ficticios
      parameters:
        - name: qty
          in: path
          description: Cantidad de productos ficticios a generar
          required: false
          schema:
            type: integer
            example: 100
      responses:
        '200':
          description: Lista de productos ficticios
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    description:
                      type: string
                    price:
                      type: number
                    thumbnails:
                      type: array
                      items:
                        type: string
                    code:
                      type: string
                    stock:
                      type: integer
                    status:
                      type: boolean
                    category:
                      type: string
        '500':
          description: Error en el servidor

  /products/{pid}:
    get:
      summary: Obtiene un producto por ID
      parameters:
        - name: pid
          in: path
          description: ID del producto a obtener
          required: true
          schema:
            type: string
            pattern: ^[a-f\d]{24}$
            example: 507f1f77bcf86cd799439011
      responses:
        '200':
          description: Información del producto
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  price:
                    type: number
                  thumbnails:
                    type: array
                    items:
                      type: string
                  code:
                    type: string
                  stock:
                    type: integer
                  status:
                    type: boolean
                  category:
                    type: string
        '400':
          description: ID no válido
        '404':
          description: Producto no encontrado
        '500':
          description: Error en el servidor

    put:
      summary: Actualiza un producto por ID
      parameters:
        - name: pid
          in: path
          description: ID del producto a actualizar
          required: true
          schema:
            type: string
            pattern: ^[a-f\d]{24}$
            example: 507f1f77bcf86cd799439011
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                price:
                  type: number
                thumbnails:
                  type: array
                  items:
                    type: string
                code:
                  type: string
                stock:
                  type: integer
                status:
                  type: boolean
                category:
                  type: string
      responses:
        '200':
          description: Producto actualizado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  price:
                    type: number
                  thumbnails:
                    type: array
                    items:
                      type: string
                  code:
                    type: string
                  stock:
                    type: integer
                  status:
                    type: boolean
                  category:
                    type: string
        '400':
          description: ID no válido o datos de entrada inválidos
        '404':
          description: Producto no encontrado
        '500':
          description: Error en el servidor

    delete:
      summary: Elimina un producto por ID
      parameters:
        - name: pid
          in: path
          description: ID del producto a eliminar
          required: true
          schema:
            type: string
            pattern: ^[a-f\d]{24}$
            example: 507f1f77bcf86cd799439011
      responses:
        '200':
          description: Producto eliminado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Producto eliminado exitosamente
        '400':
          description: ID no válido
        '404':
          description: Producto no encontrado
        '500':
          description: Error en el servidor
