version: '3.8'

services:
  app:
    env_file:
      - .env.devel
    build:
      context: .
      dockerfile: dev.dockerfile
    container_name: my_node_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${PORT}:${PORT}"
    command: sh -c "npm install && npm run dev"
    image: "${DOCKER_USER}/coder_53160:1.0.0"