version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_node_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${PORT}:${PORT}"
    command: sh -c "npm install && npx nodemon"
    env_file:
      - .env
    image: "${DOCKER_USER}/coder_53160:1.0.0"