tags:
  - name: Products
    description: Endpoints para gestionar productos

paths:
  /api/products:
    get:
      tags:
        - Products
      summary: Obtiene todos los productos
      parameters:
        - name: limit
          in: query
          description: Número de productos a devolver
          schema:
            type: integer
            example: 10
        - name: sort
          in: query
          description: Criterio de ordenamiento
          schema:
            type: string
            example: price
        - name: page
          in: query
          description: Página de resultados
          schema:
            type: integer
            example: 1
        - name: query
          in: query
          description: Consulta de búsqueda de productos
          schema:
            type: string
            example: electronics
      responses:
        "200":
          description: Lista de productos
          content:
            application/json:
              schema:
                type: object
                properties:
                  docs:
                    type: array
                    items:
                      $ref: "#/components/schemas/Product"
                  totalDocs:
                    type: integer
                  limit:
                    type: integer
                  page:
                    type: integer
                  totalPages:
                    type: integer
        "500":
          description: Error en el servidor

    post:
      tags:
        - Products
      summary: Agrega un nuevo producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
            example:
              title: "Laptop X200"
              description: "Una laptop ligera con 16GB de RAM y SSD de 512GB."
              price: 1299.99
              thumbnail: ["https://example.com/laptop1.jpg"]
              code: "LAPTOP12345"
              stock: 50
              status: true
              category: "Computadoras"
              owner: "6123456789abcdef01234567"
      responses:
        "201":
          description: Producto agregado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  origin:
                    type: string
                    example: "Id del server."
                  payload:
                    $ref: "#/components/schemas/Product"
                  message:
                    type: string
                    example: "Se ha agregado un nuevo producto."
        "400":
          description: Solicitud inválida (por ejemplo, datos de entrada no válidos)
        "500":
          description: Error en el servidor

  /api/products/fakeProducts/{qty}:
    get:
      tags:
        - Products
      summary: Genera productos ficticios
      parameters:
        - name: qty
          in: path
          description: Cantidad de productos ficticios a generar
          required: false
          schema:
            type: integer
            example: 100
      responses:
        "200":
          description: Lista de productos ficticios
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    description:
                      type: string
                    price:
                      type: number
                    thumbnails:
                      type: array
                      items:
                        type: string
                    code:
                      type: string
                    stock:
                      type: integer
                    status:
                      type: boolean
                    category:
                      type: string
        "500":
          description: Error en el servidor

  /api/products/{pid}:
    get:
      tags:
        - Products
      summary: Obtiene un producto por ID
      parameters:
        - name: pid
          in: path
          description: ID del producto a obtener
          required: true
          schema:
            type: string
            pattern: ^[a-f\d]{24}$
            example: 507f1f77bcf86cd799439011
      responses:
        "200":
          description: Información del producto
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  price:
                    type: number
                  thumbnails:
                    type: array
                    items:
                      type: string
                  code:
                    type: string
                  stock:
                    type: integer
                  status:
                    type: boolean
                  category:
                    type: string
        "400":
          description: ID no válido
        "404":
          description: Producto no encontrado
        "500":
          description: Error en el servidor

    put:
      tags:
        - Products
      summary: Actualiza un producto por ID
      parameters:
        - name: pid
          in: path
          description: ID del producto a actualizar
          required: true
          schema:
            type: string
            pattern: ^[a-f\d]{24}$
            example: 507f1f77bcf86cd799439011
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                price:
                  type: number
                thumbnails:
                  type: array
                  items:
                    type: string
                code:
                  type: string
                stock:
                  type: integer
                status:
                  type: boolean
                category:
                  type: string
      responses:
        "200":
          description: Producto actualizado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  price:
                    type: number
                  thumbnails:
                    type: array
                    items:
                      type: string
                  code:
                    type: string
                  stock:
                    type: integer
                  status:
                    type: boolean
                  category:
                    type: string
        "400":
          description: ID no válido o datos de entrada inválidos
        "404":
          description: Producto no encontrado
        "500":
          description: Error en el servidor

    delete:
      tags:
        - Products
      summary: Elimina un producto por ID
      parameters:
        - name: pid
          in: path
          description: ID del producto a eliminar
          required: true
          schema:
            type: string
            pattern: ^[a-f\d]{24}$
            example: 507f1f77bcf86cd799439011
      responses:
        "200":
          description: Producto eliminado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Producto eliminado exitosamente
        "400":
          description: ID no válido
        "404":
          description: Producto no encontrado
        "500":
          description: Error en el servidor

components:
  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        thumbnail:
          type: array
          items:
            type: string
          description: URLs de las imágenes del producto
        code:
          type: string
          description: Código único del producto
        stock:
          type: integer
          description: Stock disponible del producto
        status:
          type: boolean
          description: Estado del producto (activo o no)
        category:
          type: string
          description: Categoría del producto
        owner:
          type: string
          description: ID del propietario del producto
      required:
        - title
        - description
        - price
        - code
        - stock
        - category
        - owner
